aliases: []
creation_timestamp: 1729688977670
current_stage: None
description: null
last_updated_timestamp: 1729688977670
name: gradient_boosting
run_id: 26eb68c6c0bf47a5bc703a373706ee21
run_link: null
source: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/26eb68c6c0bf47a5bc703a373706ee21/artifacts/gradient_boosting_model
status: READY
status_message: null
storage_location: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/26eb68c6c0bf47a5bc703a373706ee21/artifacts/gradient_boosting_model
user_id: null
version: 3
