aliases: []
creation_timestamp: 1729690061740
current_stage: None
description: null
last_updated_timestamp: 1729690061740
name: gradient_boosting
run_id: 7991672311c9420da2e1413040f0958c
run_link: null
source: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/7991672311c9420da2e1413040f0958c/artifacts/gradient_boosting_model
status: READY
status_message: null
storage_location: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/7991672311c9420da2e1413040f0958c/artifacts/gradient_boosting_model
user_id: null
version: 4
