artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/78eb23890c714da0b297937578a122d8/artifacts
end_time: 1729693207895
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 78eb23890c714da0b297937578a122d8
run_name: abundant-hen-218
run_uuid: 78eb23890c714da0b297937578a122d8
source_name: ''
source_type: 4
source_version: ''
start_time: 1729691843439
status: 3
tags: []
user_id: root
