artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/71b6494496254dd7acd4f2b418039b86/artifacts
end_time: 1729690001842
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 71b6494496254dd7acd4f2b418039b86
run_name: blushing-yak-279
run_uuid: 71b6494496254dd7acd4f2b418039b86
source_name: ''
source_type: 4
source_version: ''
start_time: 1729689837591
status: 3
tags: []
user_id: root
