artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/54f4693c61054abdb758725fc83fac39/artifacts
end_time: 1729690020349
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 54f4693c61054abdb758725fc83fac39
run_name: Random Forest
run_uuid: 54f4693c61054abdb758725fc83fac39
source_name: ''
source_type: 4
source_version: ''
start_time: 1729690001875
status: 3
tags: []
user_id: root
