artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/a66b9efa9db0401aa6e69f41074aa98d/artifacts
end_time: 1729676586432
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a66b9efa9db0401aa6e69f41074aa98d
run_name: grandiose-elk-665
run_uuid: a66b9efa9db0401aa6e69f41074aa98d
source_name: ''
source_type: 4
source_version: ''
start_time: 1729676426004
status: 3
tags: []
user_id: root
