aliases: []
creation_timestamp: 1729695817351
current_stage: None
description: null
last_updated_timestamp: 1729695817351
name: random_forest
run_id: c6bfe1cafae84ccaabcc735fff902432
run_link: null
source: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/c6bfe1cafae84ccaabcc735fff902432/artifacts/random_forest_model
status: READY
status_message: null
storage_location: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/c6bfe1cafae84ccaabcc735fff902432/artifacts/random_forest_model
user_id: null
version: 6
