artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/d0e4ea0671ff4a2e9b0e41092511b729/artifacts
end_time: 1729689835128
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d0e4ea0671ff4a2e9b0e41092511b729
run_name: nimble-conch-677
run_uuid: d0e4ea0671ff4a2e9b0e41092511b729
source_name: ''
source_type: 4
source_version: ''
start_time: 1729689678051
status: 3
tags: []
user_id: root
