aliases: []
creation_timestamp: 1729691637466
current_stage: None
description: null
last_updated_timestamp: 1729691637466
name: random_forest
run_id: 53962536719f4764beb5afddacc96843
run_link: null
source: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/53962536719f4764beb5afddacc96843/artifacts/random_forest_model
status: READY
status_message: null
storage_location: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/53962536719f4764beb5afddacc96843/artifacts/random_forest_model
user_id: null
version: 5
