artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/81bceee7e39244dcaa623893fb4fc478/artifacts
end_time: 1729691462774
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 81bceee7e39244dcaa623893fb4fc478
run_name: efficient-newt-692
run_uuid: 81bceee7e39244dcaa623893fb4fc478
source_name: ''
source_type: 4
source_version: ''
start_time: 1729691321411
status: 3
tags: []
user_id: root
