artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/a0182b876984478bb8c297de5eb38962/artifacts
end_time: 1729676775362
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a0182b876984478bb8c297de5eb38962
run_name: magnificent-ram-684
run_uuid: a0182b876984478bb8c297de5eb38962
source_name: ''
source_type: 4
source_version: ''
start_time: 1729676586452
status: 3
tags: []
user_id: root
