artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/3ed823c8d86d43d6b66ec1a3954e2843/artifacts
end_time: 1729688763193
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 3ed823c8d86d43d6b66ec1a3954e2843
run_name: upbeat-kit-768
run_uuid: 3ed823c8d86d43d6b66ec1a3954e2843
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688620010
status: 3
tags: []
user_id: root
