aliases: []
creation_timestamp: 1729676836896
current_stage: None
description: null
last_updated_timestamp: 1729676836896
name: gradient_boosting
run_id: 97227889143f453589290ff12377f0b4
run_link: null
source: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/97227889143f453589290ff12377f0b4/artifacts/gradient_boosting_model
status: READY
status_message: null
storage_location: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/97227889143f453589290ff12377f0b4/artifacts/gradient_boosting_model
user_id: null
version: 1
