aliases: []
creation_timestamp: 1729690020256
current_stage: None
description: null
last_updated_timestamp: 1729690020256
name: random_forest
run_id: 54f4693c61054abdb758725fc83fac39
run_link: null
source: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/54f4693c61054abdb758725fc83fac39/artifacts/random_forest_model
status: READY
status_message: null
storage_location: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/54f4693c61054abdb758725fc83fac39/artifacts/random_forest_model
user_id: null
version: 4
