artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/8f8387c8ea06423aa4f307e3a56f014b/artifacts
end_time: 1729691465353
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 8f8387c8ea06423aa4f307e3a56f014b
run_name: unique-fly-55
run_uuid: 8f8387c8ea06423aa4f307e3a56f014b
source_name: ''
source_type: 4
source_version: ''
start_time: 1729691321411
status: 3
tags: []
user_id: root
