artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/39d47c9c5fa24f2483232bbe419753fb/artifacts
end_time: 1729676584303
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 39d47c9c5fa24f2483232bbe419753fb
run_name: traveling-skink-473
run_uuid: 39d47c9c5fa24f2483232bbe419753fb
source_name: ''
source_type: 4
source_version: ''
start_time: 1729676426004
status: 3
tags: []
user_id: root
