artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/cadc1f9b812840df96f31e833eb58fdf/artifacts
end_time: 1729691793856
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: cadc1f9b812840df96f31e833eb58fdf
run_name: LSTM
run_uuid: cadc1f9b812840df96f31e833eb58fdf
source_name: ''
source_type: 4
source_version: ''
start_time: 1729691678119
status: 3
tags: []
user_id: root
