artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/1e7b781e18d44186b991390ac56e2f27/artifacts
end_time: 1729688578992
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 1e7b781e18d44186b991390ac56e2f27
run_name: CNN
run_uuid: 1e7b781e18d44186b991390ac56e2f27
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688529742
status: 3
tags: []
user_id: root
