artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/c9a3405700c149018aca11290609bdca/artifacts
end_time: 1729676584303
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c9a3405700c149018aca11290609bdca
run_name: entertaining-bat-974
run_uuid: c9a3405700c149018aca11290609bdca
source_name: ''
source_type: 4
source_version: ''
start_time: 1729676426004
status: 3
tags: []
user_id: root
