artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/b55ce3d48ea64643ad44beb437c9146a/artifacts
end_time: 1729691462774
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b55ce3d48ea64643ad44beb437c9146a
run_name: skittish-hen-562
run_uuid: b55ce3d48ea64643ad44beb437c9146a
source_name: ''
source_type: 4
source_version: ''
start_time: 1729691321411
status: 3
tags: []
user_id: root
