artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/ce7878b3903745c580be0f5277f05bb5/artifacts
end_time: 1729688200168
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ce7878b3903745c580be0f5277f05bb5
run_name: crawling-hound-169
run_uuid: ce7878b3903745c580be0f5277f05bb5
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688041554
status: 3
tags: []
user_id: root
