aliases: []
creation_timestamp: 1729696244813
current_stage: None
description: null
last_updated_timestamp: 1729696244813
name: gradient_boosting
run_id: 8620ca2c2904477a8d689d0e22fcff2e
run_link: null
source: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/8620ca2c2904477a8d689d0e22fcff2e/artifacts/gradient_boosting_model
status: READY
status_message: null
storage_location: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/8620ca2c2904477a8d689d0e22fcff2e/artifacts/gradient_boosting_model
user_id: null
version: 6
