artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/6780c778a1ec481c8d44e27859f7dfeb/artifacts
end_time: 1729691618719
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6780c778a1ec481c8d44e27859f7dfeb
run_name: stylish-mule-367
run_uuid: 6780c778a1ec481c8d44e27859f7dfeb
source_name: ''
source_type: 4
source_version: ''
start_time: 1729691465376
status: 3
tags: []
user_id: root
