artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/421e6b2336e6447f97e8448df7147d59/artifacts
end_time: 1729689999887
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 421e6b2336e6447f97e8448df7147d59
run_name: calm-finch-195
run_uuid: 421e6b2336e6447f97e8448df7147d59
source_name: ''
source_type: 4
source_version: ''
start_time: 1729689837591
status: 3
tags: []
user_id: root
