artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/c6bfe1cafae84ccaabcc735fff902432/artifacts
end_time: 1729695817437
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c6bfe1cafae84ccaabcc735fff902432
run_name: Random Forest
run_uuid: c6bfe1cafae84ccaabcc735fff902432
source_name: ''
source_type: 4
source_version: ''
start_time: 1729695537189
status: 3
tags: []
user_id: root
