artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/e4995fa47fad48c18363da6caa23a63b/artifacts
end_time: 1729688919900
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e4995fa47fad48c18363da6caa23a63b
run_name: handsome-rat-403
run_uuid: e4995fa47fad48c18363da6caa23a63b
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688765721
status: 3
tags: []
user_id: root
