aliases: []
creation_timestamp: 1729696462192
current_stage: None
description: null
last_updated_timestamp: 1729696462192
name: lstm
run_id: 7edd78804cc14dfd8d6718392765fc76
run_link: null
source: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/7edd78804cc14dfd8d6718392765fc76/artifacts/lstm_model
status: READY
status_message: null
storage_location: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/7edd78804cc14dfd8d6718392765fc76/artifacts/lstm_model
user_id: null
version: 5
