artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/9f0be561263647df9ff0ac3fda84e2d2/artifacts
end_time: 1729688357415
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9f0be561263647df9ff0ac3fda84e2d2
run_name: invincible-shark-770
run_uuid: 9f0be561263647df9ff0ac3fda84e2d2
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688202451
status: 3
tags: []
user_id: root
