artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/dcbaed411a5a4ae9819351b030992184/artifacts
end_time: 1729688200168
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: dcbaed411a5a4ae9819351b030992184
run_name: skittish-hog-182
run_uuid: dcbaed411a5a4ae9819351b030992184
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688041554
status: 3
tags: []
user_id: root
