artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/f98a9fbbf3c3424d8fbf9a2abd05ad49/artifacts
end_time: 1729688200168
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f98a9fbbf3c3424d8fbf9a2abd05ad49
run_name: intrigued-ox-491
run_uuid: f98a9fbbf3c3424d8fbf9a2abd05ad49
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688041554
status: 3
tags: []
user_id: root
