artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/d914fac7f91a44ecafd067f3faffeded/artifacts
end_time: 1729688200168
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d914fac7f91a44ecafd067f3faffeded
run_name: rebellious-eel-845
run_uuid: d914fac7f91a44ecafd067f3faffeded
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688041554
status: 3
tags: []
user_id: root
