artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/739a11612883436bbb9edf7267ac3ed4/artifacts
end_time: 1729691462774
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 739a11612883436bbb9edf7267ac3ed4
run_name: adventurous-hare-37
run_uuid: 739a11612883436bbb9edf7267ac3ed4
source_name: ''
source_type: 4
source_version: ''
start_time: 1729691321411
status: 3
tags: []
user_id: root
