artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/e9b2a4ab37244b5188348cf0b56ec576/artifacts
end_time: 1729691462774
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e9b2a4ab37244b5188348cf0b56ec576
run_name: selective-squid-516
run_uuid: e9b2a4ab37244b5188348cf0b56ec576
source_name: ''
source_type: 4
source_version: ''
start_time: 1729691321411
status: 3
tags: []
user_id: root
