artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/4446d1da74a4474fb8c744c5377a693a/artifacts
end_time: 1729689075165
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4446d1da74a4474fb8c744c5377a693a
run_name: LSTM
run_uuid: 4446d1da74a4474fb8c744c5377a693a
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688977748
status: 3
tags: []
user_id: root
