artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/4e64dc8605814d65860a602c78d218ef/artifacts
end_time: 1729695534891
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4e64dc8605814d65860a602c78d218ef
run_name: gifted-wolf-430
run_uuid: 4e64dc8605814d65860a602c78d218ef
source_name: ''
source_type: 4
source_version: ''
start_time: 1729693207919
status: 3
tags: []
user_id: root
