artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/4b74a770f88541cca84f04fb40bef47b/artifacts
end_time: 1729691618719
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4b74a770f88541cca84f04fb40bef47b
run_name: bright-toad-250
run_uuid: 4b74a770f88541cca84f04fb40bef47b
source_name: ''
source_type: 4
source_version: ''
start_time: 1729691465376
status: 3
tags: []
user_id: root
