artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/656522c462c84c10885ceccb805b5e36/artifacts
end_time: 1729693205399
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 656522c462c84c10885ceccb805b5e36
run_name: bold-lynx-109
run_uuid: 656522c462c84c10885ceccb805b5e36
source_name: ''
source_type: 4
source_version: ''
start_time: 1729691843439
status: 3
tags: []
user_id: root
