artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/ac3a7524a82a4bfe96d30437342cb7eb/artifacts
end_time: 1729695534891
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ac3a7524a82a4bfe96d30437342cb7eb
run_name: rebellious-yak-469
run_uuid: ac3a7524a82a4bfe96d30437342cb7eb
source_name: ''
source_type: 4
source_version: ''
start_time: 1729693207919
status: 3
tags: []
user_id: root
