artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/6cadcc1a7edd4dc493fdf623c82df77c/artifacts
end_time: 1729688357415
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6cadcc1a7edd4dc493fdf623c82df77c
run_name: fortunate-cod-329
run_uuid: 6cadcc1a7edd4dc493fdf623c82df77c
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688202451
status: 3
tags: []
user_id: root
