aliases: []
creation_timestamp: 1729688529673
current_stage: None
description: null
last_updated_timestamp: 1729688529673
name: lstm
run_id: 4494e871606549ecbf57a9cbbc0c28c0
run_link: null
source: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/4494e871606549ecbf57a9cbbc0c28c0/artifacts/lstm_model
status: READY
status_message: null
storage_location: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/4494e871606549ecbf57a9cbbc0c28c0/artifacts/lstm_model
user_id: null
version: 1
