artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/f7cdd7a58e594872baa06364ac33f910/artifacts
end_time: 1729690173816
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f7cdd7a58e594872baa06364ac33f910
run_name: LSTM
run_uuid: f7cdd7a58e594872baa06364ac33f910
source_name: ''
source_type: 4
source_version: ''
start_time: 1729690061836
status: 3
tags: []
user_id: root
