artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/209b145e65cc4f8683f126ff39f2eafb/artifacts
end_time: 1729688357415
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 209b145e65cc4f8683f126ff39f2eafb
run_name: silent-roo-180
run_uuid: 209b145e65cc4f8683f126ff39f2eafb
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688202451
status: 3
tags: []
user_id: root
