artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/26eb68c6c0bf47a5bc703a373706ee21/artifacts
end_time: 1729688977729
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 26eb68c6c0bf47a5bc703a373706ee21
run_name: Gradient Boosting
run_uuid: 26eb68c6c0bf47a5bc703a373706ee21
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688940093
status: 3
tags: []
user_id: root
