artifact_location: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0
creation_time: 1729676048190
experiment_id: '0'
last_update_time: 1729676048190
lifecycle_stage: active
name: Default
