artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/a77f691d96ac4b1082a8d60d0b84177d/artifacts
end_time: 1729688763193
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a77f691d96ac4b1082a8d60d0b84177d
run_name: clumsy-vole-166
run_uuid: a77f691d96ac4b1082a8d60d0b84177d
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688620010
status: 3
tags: []
user_id: root
