artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/4494e871606549ecbf57a9cbbc0c28c0/artifacts
end_time: 1729688529710
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4494e871606549ecbf57a9cbbc0c28c0
run_name: LSTM
run_uuid: 4494e871606549ecbf57a9cbbc0c28c0
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688422853
status: 3
tags: []
user_id: root
