artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/fc9a0c89d228414d924b619c6a36d5b9/artifacts
end_time: 1729695534891
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: fc9a0c89d228414d924b619c6a36d5b9
run_name: adorable-panda-394
run_uuid: fc9a0c89d228414d924b619c6a36d5b9
source_name: ''
source_type: 4
source_version: ''
start_time: 1729693207919
status: 3
tags: []
user_id: root
