artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/8205572dddbf447589faff0fb7f8e2d1/artifacts
end_time: 1729688763193
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 8205572dddbf447589faff0fb7f8e2d1
run_name: wistful-gull-884
run_uuid: 8205572dddbf447589faff0fb7f8e2d1
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688620010
status: 3
tags: []
user_id: root
