artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/9168e4a746cd4150bcf446753f305d5b/artifacts
end_time: 1729689999887
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9168e4a746cd4150bcf446753f305d5b
run_name: classy-kite-288
run_uuid: 9168e4a746cd4150bcf446753f305d5b
source_name: ''
source_type: 4
source_version: ''
start_time: 1729689837591
status: 3
tags: []
user_id: root
