aliases: []
creation_timestamp: 1729688578957
current_stage: None
description: null
last_updated_timestamp: 1729688578957
name: cnn
run_id: 1e7b781e18d44186b991390ac56e2f27
run_link: null
source: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/1e7b781e18d44186b991390ac56e2f27/artifacts/cnn_model
status: READY
status_message: null
storage_location: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/1e7b781e18d44186b991390ac56e2f27/artifacts/cnn_model
user_id: null
version: 1
