artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/bb564b0c5c4d405381aa6ef8fdb349d0/artifacts
end_time: 1729693205399
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: bb564b0c5c4d405381aa6ef8fdb349d0
run_name: serious-hawk-593
run_uuid: bb564b0c5c4d405381aa6ef8fdb349d0
source_name: ''
source_type: 4
source_version: ''
start_time: 1729691843439
status: 3
tags: []
user_id: root
