aliases: []
creation_timestamp: 1729691676068
current_stage: None
description: null
last_updated_timestamp: 1729691676068
name: gradient_boosting
run_id: b31557eefc314e23aa5ac535ae6407d9
run_link: null
source: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/b31557eefc314e23aa5ac535ae6407d9/artifacts/gradient_boosting_model
status: READY
status_message: null
storage_location: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/b31557eefc314e23aa5ac535ae6407d9/artifacts/gradient_boosting_model
user_id: null
version: 5
