artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/df8946a4d89441859a57960b6fed4071/artifacts
end_time: 1729689999887
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: df8946a4d89441859a57960b6fed4071
run_name: efficient-quail-395
run_uuid: df8946a4d89441859a57960b6fed4071
source_name: ''
source_type: 4
source_version: ''
start_time: 1729689837591
status: 3
tags: []
user_id: root
