artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/8903225becce4e1398ca1a01a011317e/artifacts
end_time: 1729676584303
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 8903225becce4e1398ca1a01a011317e
run_name: adorable-ray-849
run_uuid: 8903225becce4e1398ca1a01a011317e
source_name: ''
source_type: 4
source_version: ''
start_time: 1729676426004
status: 3
tags: []
user_id: root
