artifact_uri: file:///content/drive/MyDrive/Colab%20Notebooks/fraud_detection_project/notebooks/mlruns/0/4fabf722e6774e9784165c5f8fc18d5b/artifacts
end_time: 1729688763193
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4fabf722e6774e9784165c5f8fc18d5b
run_name: amusing-squirrel-137
run_uuid: 4fabf722e6774e9784165c5f8fc18d5b
source_name: ''
source_type: 4
source_version: ''
start_time: 1729688620010
status: 3
tags: []
user_id: root
